
    
[context.production.environment]
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"



[context.split1.environment]
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"



[context.deploy-preview.environment]
HUGO_VERSION = "0.79.0"


[context.branch-deploy.environment]
HUGO_VERSION = "0.79.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
